version: '3.7'

volumes:
  rails_cache:
  bundle:
  node_modules:
  packs:

services:
  camelan: &camelan
    container_name: camelan
    hostname: camelan
    image: camelan
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_USER_ID: ${APP_USER_ID}
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    volumes:
      - .:/home/camelan/camelan:cached
      - ~/.ssh:/home/camelan/.ssh
      - rails_cache:/home/camelan/camelan/tmp/cache
      - bundle:/bundle
      - node_modules:/home/camelan/camelan/node_modules
      - packs:/home/camelan/camelan/public/packs
    tmpfs:
      - /tmp
    env_file: .env
    entrypoint: ["/home/camelan/docker-entrypoint.sh"]
    command: ["bundle", "exec", "rails","server","-b","0.0.0.0","-p","3000"]
