---
swagger: '2.0'
info:
  title: Camelan APIs
  description: This is the description of the API
  version: v1
paths:
  "/api/v1/users/{user_id}/pets/{pet_id}/bids":
    post:
      summary: create bid
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: user_id
        in: path
        type: integer
        required: true
      - name: pet_id
        in: path
        type: integer
        required: true
      - name: bid
        in: body
        schema:
          type: object
          properties:
            bid_price:
              type: string
            user_id:
              type: string
      responses:
        '200':
          description: create bid succefully
    get:
      summary: list all pet bids
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: user_id
        in: path
        type: integer
        required: true
      - name: pet_id
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: create bid succefully
